
version: '3.8'

services:
  db_local:
    image: postgres:13.12-alpine3.18
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: db_local
    volumes:
      - ./postgres:/var/lib/postgresql/data


