
version: '3'

services:
  funnel_escala_db:
    image: postgres:15.4-alpine3.18
    restart: always
    ports:
      - "3350:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    container_name: funnel_escala_db
    volumes:
      - ./mysql:/var/lib/mysql

