# version: '3'

# services:
#   funnel_escala_db:
#     image: mysql:latest
#     restart: always
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#       MYSQL_DATABASE: ${DB_NAME}
#     container_name: funnel_escala_db
#     volumes:
#       - ./mysql:/var/lib/mysql

version: '3'

services:
  funnel_escala_db:
    image: mysql:8.0.33
    restart: always
    ports:
      - "3350:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    container_name: funnel_escala_db
    volumes:
      - ./mysql:/var/lib/mysql



# version: '3'

# services:
#   dynamodb:
#     image: amazon/dynamodb-local
#     hostname: dynamodblocal
#     ports:
#       - "8000:8000"
#     expose:
#       - "8000"
#     container_name: dynamodb-local
#     command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
#     volumes:
#       - ./dynamodb-data:/data
#     environment:
#       - AWS_ACCESS_KEY_ID= ${AWS_ACCESS_KEY_ID}
#       - AWS_SECRET_ACCESS_KEY= ${AWS_SECRET_ACCESS_KEY}
#       - AWS_DEFAULT_REGION= ${AWS_REGION}

