export enum _Configuration_Keys {
    JWT_SECRET = "JWT_SECRET",
    PORT = "PORT",
    LOG_LEVEL = "LOG_LEVEL",
    ENVIROMENT = "ENVIROMENT",
    ALLOWEDORIGINS = "ALLOWEDORIGINS",
    EMAILTEST = "EMAILTEST",
    EMAILINFO = "EMAILINFO",
    DEFAULT_LIMIT = "DEFAULT_LIMIT",

    AWS_ACCESS_KEY_ID = "AWS_ACCESS_KEY_ID",
    AWS_SECRET_ACCESS_KEY = "AWS_SECRET_ACCESS_KEY",
    AWS_REGION = "AWS_REGION",

    IS_DDB_LOCAL = "IS_DDB_LOCAL",
    SERVICE = "SERVICE",
    STAGE = "STAGE",
    REGION = "REGION",


    IDENTITYPOOLID = "IDENTITYPOOLID",
    USERPOOLID = "USERPOOLID",
    USERPOOLWEBCLIENTID = "USERPOOLWEBCLIENTID",

    DB_PASSWORD = "DB_PASSWORD",
    DB_NAME = "DB_NAME",
    DB_HOST = "DB_HOST",
    DB_PORT = "DB_PORT",
    DB_USERNAME = "DB_USERNAME",

    NODE_ENV = "NODE_ENV"

}


